config/routes.rb
Cxe::Application.routes.draw do
  get "users/new"

  get "welcome/index"

  resources :branches, :stocks, :users
  resources :transactions
  match 'tran/stockin',  to: 'transactions#newstockin',         via: 'get'
  match 'tran/stockin',  to: 'transactions#createstockin',      via: 'post'
  match 'tran/buy',  to: 'transactions#newbuy',         via: 'get'
  match 'tran/buy',  to: 'transactions#createbuy',      via: 'post'
  match 'tran/sell',  to: 'transactions#newsell',         via: 'get'
  match 'tran/sell',  to: 'transactions#createsell',      via: 'post'
  
  
  match 'tran/getrate/:currid',  to: 'transactions#getrate',         via: 'get'
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  resources :currencies do
	collection { post :import }
  end
  
  root :to => 'sessions#new'

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  attr_accessible :address, :city, :name, :state
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
layout 'standard'
before_filter :signed_in_user
def new
	@branch = Branch.new
end

 def create
	@branch = Branch.new(params[:branch])
 
	if @branch.save
		redirect_to @branch
	else
		render 'new'
	end
 end
 
 def update
  @branch = Branch.find(params[:id])
 
  if @branch.update_attributes(params[:branch])
    redirect_to @branch
  else
    render 'edit'
  end
 end
 
 def destroy
  @branch = Branch.find(params[:id])
  @branch.destroy
 
  redirect_to branches_path
end
  
 def show
  @branch = Branch.find(params[:id])
end 

def index
  @branches = Branch.all
end
	
def edit
  @branch = Branch.find(params[:id])
end

private 
	def signed_in_user
      redirect_to signin_path, notice: "Please sign in." unless signed_in?
    end	


end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<%= form_for @branch do |b| %>
  <p>
    <%= b.label :Name %><br>
    <%= b.text_field :name %>
  </p>
 
  <p>
    <%= b.label :City %><br>
    <%= b.text_field :city %>
  </p>
 
   <p>
    <%= b.label :State %><br>
    <%= b.text_field :state %>
  </p>
  
   <p>
    <%= b.label :Address %><br>
    <%= b.text_field :address %>
  </p>
  
  <p>
    <%= b.submit %>
  </p>
<% end %>

app/views/branches/edit.html.erb
<h> New Branch <h>

<%= render 'form' %>
 
<%= link_to 'Back', branches_path %>

app/views/branches/index.html.erb
<h1>Listing Branches</h1>

<%= link_to 'New Branch', new_branch_path %> 
 
<table class="gridtable">
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>State</th>
    <th>Address</th>
  </tr>
 
  <% @branches.each do |branch| %>
    <tr>
      <td><%= branch.name %></td>
      <td><%= branch.city %></td>
      <td><%= branch.state %></td>
      <td><%= branch.address %></td>
	  <td><%= link_to 'Show', branch_path(branch) %></td>
	  <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
	  <td><%= link_to 'Destroy', branch_path(branch),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/branches/new.html.erb
<h1> New Branch <h1>

<%= render 'form' %>
 
<%= link_to 'Back', branches_path %>

app/views/branches/show.html.erb
<h> Branch <h>
<p>
  <strong>Name:</strong>
  <%= @branch.name %>
</p>
<p>
  <strong>City:</strong>
  <%= @branch.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @branch.state %>
</p>
<p>
  <strong>Address:</strong>
  <%= @branch.address %>
</p>

<%= link_to 'Back', branches_path %> | <%= link_to 'Edit', edit_branch_path(@branch) %>