config/routes.rb
Cxe::Application.routes.draw do
  get "users/new"

  get "welcome/index"

  resources :branches, :stocks, :users
  resources :transactions
  match 'tran/stockin',  to: 'transactions#newstockin',         via: 'get'
  match 'tran/stockin',  to: 'transactions#createstockin',      via: 'post'
  match 'tran/buy',  to: 'transactions#newbuy',         via: 'get'
  match 'tran/buy',  to: 'transactions#createbuy',      via: 'post'
  match 'tran/sell',  to: 'transactions#newsell',         via: 'get'
  match 'tran/sell',  to: 'transactions#createsell',      via: 'post'
  
  
  match 'tran/getrate/:currid',  to: 'transactions#getrate',         via: 'get'
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  resources :currencies do
	collection { post :import }
  end
  
  root :to => 'sessions#new'

end

app/models/currency.rb
class Currency < ActiveRecord::Base
  attr_accessible :buyrate, :currencycode, :currencyname, :sellrate
  
  validates :currencyname, presence: true,
                    length: { maximum: 50 }

  validates :currencycode, presence: true,
                    length: { maximum: 5 }

  validates :buyrate, presence: true,
                    length: { maximum: 8 },
					:numericality => { :greater_than_or_equal_to => 0 }

  validates :sellrate, presence: true,
                    length: { maximum: 8 },
					:numericality => { :greater_than_or_equal_to => 0 }
					
	

def self.import(file)
  spreadsheet = open_spreadsheet(file)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i|
    row = Hash[[header, spreadsheet.row(i)].transpose]
    #currency = find_by_currencycode(row["currencycode"]) || new
    currency = Currency.where(:currencycode => row["currencycode"]).where(:currencyname => row["currencyname"]).first || new
	currency.attributes = row.to_hash.slice(*accessible_attributes)
    currency.save!
  end
end

def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Csv.new(file.path, nil, :ignore)
  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
  else raise "Unknown file type: #{file.original_filename}"
  end
end
	
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
layout 'standard'
before_filter :signed_in_user

def new
	@currency = Currency.new
end

 def create
	@currency = Currency.new(params[:currency])
 
	if @currency.save
		redirect_to @currency
	else
		render 'new'
	end
 end
 
 def update
  @currency = Currency.find(params[:id])
 
  if @currency.update_attributes(params[:currency])
    redirect_to @currency
  else
    render 'edit'
  end
 end
 
 def destroy
  @currency = Currency.find(params[:id])
  @currency.destroy
 
  redirect_to currencies_path
end
  
 def show
  @currency = Currency.find(params[:id])
end 

def index
  @currencies = Currency.all
end
	
def edit
  @currency = Currency.find(params[:id])
end
	
def import
  Currency.import(params[:file])
  redirect_to currencies_path, notice: "Products imported."
end
	
	
private 
	def signed_in_user
      redirect_to signin_path, notice: "Please sign in." unless signed_in?
    end	
	
end

app/helpers/currency_helper.rb
module CurrencyHelper
end

app/views/currencies/edit.html.erb
<h1>Editing Currency</h1>
 
<%= form_for :currency, url: currency_path(@currency.id) , method: :put do |c| %>

<% if @currency.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@currency.errors.count, "error") %> prohibited
      this currency from being saved:</h2>
    <ul>
    <% @currency.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= c.label :'Currency Name' %><br>
    <%= c.text_field :currencyname %>
  </p>
 
  <p>
    <%= c.label :'Currency Code' %><br>
    <%= c.text_field :currencycode %>
  </p>
 
  <p>
    <%= c.label :'Buying Rate' %><br>
    <%= c.text_field :buyrate %>
  </p>
 
 <p>
    <%= c.label :'Selling Rate' %><br>
    <%= c.text_field :sellrate %>
 </p>
 
 
  <p>
    <%= c.submit %>
  </p>
<% end %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<h1>Import Products</h1>

<%= form_tag import_currencies_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<h1>Listing Currencies</h1>


<table class="gridtable">
  <tr>
    <th>Name</th>
    <th>Code</th>
	<th>Buy Rate</th>
    <th>Sell Rate</th>
  </tr>

  <% @currencies.each do |currency| %>
    <tr>
      <td><%= currency.currencyname %></td>
      <td><%= currency.currencycode %></td>
      <td><%= currency.buyrate %></td>
      <td><%= currency.sellrate %></td>
	  <td><%= link_to 'Show', currency_path(currency) %></td>
	  <td><%= link_to 'Edit', edit_currency_path(currency) %></td>
	  <td><%= link_to 'Destroy', currency_path(currency),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New currency', new_currency_path %> 

app/views/currencies/new.html.erb
<%= form_for :currency, url: currencies_path do |c| %>

<% if @currency.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@currency.errors.count, "error") %> prohibited
      this currency from being saved:</h2>
    <ul>
    <% @currency.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= c.label :'Currency Name' %><br>
    <%= c.text_field :currencyname %>
  </p>
 
  <p>
    <%= c.label :'Currency Code' %><br>
    <%= c.text_field :currencycode %>
  </p>
 
  <p>
    <%= c.label :'Buying Rate' %><br>
    <%= c.text_field :buyrate %>
  </p>
 
 <p>
    <%= c.label :'Selling Rate' %><br>
    <%= c.text_field :sellrate %>
 </p>
 
 
  <p>
    <%= c.submit %>
  </p>
<% end %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<p>
  <strong>Currency Name:</strong>
  <%= @currency.currencyname %>
</p>
<p>
  <strong>Currency Code:</strong>
  <%= @currency.currencycode %>
</p>

<p>
  <strong>Buying Rate:</strong>
  <%= @currency.buyrate %>
</p>
<p>
  <strong>Selling Rate:</strong>
  <%= @currency.sellrate %>
</p>

<%= link_to 'Back', currencies_path %> | <%= link_to 'Edit', edit_currency_path(@currency) %>