config/routes.rb
Cxe::Application.routes.draw do
  get "users/new"

  get "welcome/index"

  resources :branches, :stocks, :users
  resources :transactions
  match 'tran/stockin',  to: 'transactions#newstockin',         via: 'get'
  match 'tran/stockin',  to: 'transactions#createstockin',      via: 'post'
  match 'tran/buy',  to: 'transactions#newbuy',         via: 'get'
  match 'tran/buy',  to: 'transactions#createbuy',      via: 'post'
  match 'tran/sell',  to: 'transactions#newsell',         via: 'get'
  match 'tran/sell',  to: 'transactions#createsell',      via: 'post'
  
  
  match 'tran/getrate/:currid',  to: 'transactions#getrate',         via: 'get'
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  resources :currencies do
	collection { post :import }
  end
  
  root :to => 'sessions#new'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
layout 'standard'
before_filter :signed_in_user


def newstockin
	@transaction = Transaction.new
end

def newbuy
	@transaction = Transaction.new
end

def newsell
	@transaction = Transaction.new
end

def show
  @transaction = Transaction.find(params[:id])
end 

 def index
  @transactions = Transaction.all
end

def destroy
  @transaction = Transaction.find(params[:id])
  @transaction.destroy
 
  redirect_to transactions_path
end

def createstockin
	@transaction = Transaction.new(params[:transaction])
	@transaction.totalamt = @transaction.amount
	@transaction.trantype = 'Stock In'
	savetransaction @transaction
end

def createbuy
	#render text: params[:transaction].inspect
	@transaction = Transaction.new(params[:transaction])
	@transaction.trantype = 'Buy'
	savetransaction @transaction
end

def createsell
	@transaction = Transaction.new(params[:transaction])
	@transaction.trantype = 'Sell'
	savetransaction @transaction
end

def getrate
	@currency = Currency.where(:id => params[:currid]).first
	render text: @currency.buyrate
end

private 
	def signed_in_user
      redirect_to signin_path, notice: "Please sign in." unless signed_in?
    end	

	def savetransaction(transaction)
		@transaction.branch_id = @current_user.branch_id
		@transaction.user_id = @current_user.id
 
		if @transaction.save
			stock = Stock.find_or_initialize_by_currency_id_and_branch_id(@transaction.currency_id, @transaction.branch_id)
			#stock = Stock.where(:currency_id => @transaction.currency_id).where(:branch_id => @transaction.branch_id).first
			if @transaction.trantype == 'Stock In' || @transaction.trantype == 'Buy'  	
				stock.currentbalance =  @transaction.amount + (stock.currentbalance == nil ? 0 : stock.currentbalance)
				stock.openingbalance =   (stock.openingbalance == nil ? 0 :stock.openingbalance)
			else
				stock.currentbalance = (stock.currentbalance == nil ? 0 : stock.currentbalance) - @transaction.amount
				stock.openingbalance =   (stock.openingbalance == nil ? 0 :stock.openingbalance)
			end
			stock.save
			redirect_to @transaction
		else
			render 'new'
		end
	end
	
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/index.html.erb
<h1>Transactions Listing</h1>

<table class="gridtable">
  <tr>
    <th>Currency Code</th>
    <th>Branch Name</th>
    <th>Amount</th>
    <th>Rate Applied</th>
	<th>Commission</th>
	<th>Total Amount</th>	
    <th>Transaction Type</th>
	<th>User</th>
</tr>
 
  <% @transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.currency.currencycode %></td>
      <td><%= transaction.branch.name %></td>
	  <td><%= transaction.amount %></td>
	  <td><%= transaction.actualrate %></td>
	  <td><%= transaction.comission %></td>
      <td><%= transaction.totalamt %></td>
 	  <td><%= transaction.trantype %></td>
      <td><%= transaction.user.name %></td>
   
	  <td><%= link_to 'Show', transaction_path(transaction) %></td>
	  <td><%= link_to 'Destroy', transaction_path(transaction),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>


app/views/transactions/newbuy.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
</script>
<script>
$(document).ready(function(){
  $("#transaction_currency_id").change(function(){
    $.get("getrate/"+document.getElementById("transaction_currency_id").value,function(data,status){
      document.getElementById("transaction_actualrate").value= data
    });
  });


 $("#transaction_amount,#transaction_comission,#transaction_actualrate,#pa,#fx").change(function(){
	if( document.getElementById("transaction_actualrate").value != ''){
		
		var converted = parseFloat(document.getElementById("transaction_amount").value / document.getElementById("transaction_actualrate").value  ) ;
		var com_val;
		if (document.getElementById('pa').checked) {
			com_val = converted * parseFloat(document.getElementById("transaction_comission").value)  /100  ;
		}else{
			com_val = parseFloat(document.getElementById("transaction_comission").value);
		}
		
		var total = converted - com_val;
		
		document.getElementById("convertedval").value = converted
		document.getElementById("transaction_totalamt").value = total
	}
  });
  
  
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });
  
});

</script>

<h1> Buy Currency </h1>
<%= form_for :transaction, url: tran_buy_path do |s| %>

<% if @transaction.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited
      this transaction from being saved:</h2>
    <ul>
    <% @transaction.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<table>
<tr>
<td>  
  <p>
	<%= s.label :'Branch: '%>
	<%= @current_user.branch.name %>
  </p>
</td>
</tr>

<tr>
<td>  
  <p>
	<%= s.label :'Currency Code'%><br>
	<%= collection_select(:transaction, :currency_id, Currency.all, :id, :currencycode, {prompt: true}) %>
  </p>
</td>
</tr>  

<tr>
<td>  
  <p>
	<%= s.label :'Rate'%><br>
	<%= s.number_field :actualrate, :readonly => true %>
  </p>
</td>  
</tr>  

<tr>
<td>  
  <p>
	<%= s.label :'Amount'%><br>
	<%= s.number_field :amount %>
  </p>
</td> 

<td>  
  <p>
	<label>Converted</label><br>
	<input type="number" id="convertedval" name="convertedval" readonly= "readonly">
  </p>
</td> 
</tr> 

<tr>
<td>  
   <p>
	<%= s.label :'Commission'%><br>
	<%= s.number_field :comission, :value =>6 %>
   </p>
</td>
<td>
   <p>
	<input type="radio" id= "fx" name="com" value="fixed" checked="checked">Fixed
	<input type="radio" id= "pa"  name="com" value="percentage">Percentage
  </p>
</td> 
</tr>

<tr>
<td>
  <p>
	<%= s.label :'Total'%><br>
	<%= s.text_field :totalamt, :readonly => true %>
  </p>
</td>
</tr>
</table>  
 <p>
    <%= s.submit %>
  </p>

  
<% end %>


<%= link_to 'Back', currencies_path %>

app/views/transactions/newsell.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
</script>
<script>
$(document).ready(function(){
  $("#transaction_currency_id").change(function(){
    $.get("getrate/"+document.getElementById("transaction_currency_id").value,function(data,status){
      document.getElementById("transaction_actualrate").value= data
    });
  });


 $("#transaction_amount,#transaction_comission,#transaction_actualrate,#pa,#fx").change(function(){
	if( document.getElementById("transaction_actualrate").value != ''){
		
		var converted = parseFloat(document.getElementById("transaction_amount").value / document.getElementById("transaction_actualrate").value  ) ;
		var com_val;
		if (document.getElementById('pa').checked) {
			com_val = converted * parseFloat(document.getElementById("transaction_comission").value)  /100  ;
		}else{
			com_val = parseFloat(document.getElementById("transaction_comission").value);
		}
		
		var total = converted + com_val;
		
		document.getElementById("convertedval").value = converted
		document.getElementById("commval").value = com_val
		document.getElementById("transaction_totalamt").value = total
	}
  });
  
  
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });
  
});

</script>

<h1> Buy Currency </h1>
<%= form_for :transaction, url: tran_sell_path do |s| %>

<% if @transaction.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited
      this transaction from being saved:</h2>
    <ul>
    <% @transaction.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<table>
<tr>
<td>  
  <p>
	<%= s.label :'Branch: '%>
	<%= @current_user.branch.name %>
  </p>
</td>
</tr>

<tr>
<td>  
  <p>
	<%= s.label :'Currency Code'%><br>
	<%= collection_select(:transaction, :currency_id, Currency.all, :id, :currencycode, {prompt: true}) %>
  </p>
</td>
</tr>  

<tr>
<td>  
  <p>
	<%= s.label :'Rate'%><br>
	<%= s.number_field :actualrate, :readonly => true %>
  </p>
</td>  
</tr>  

<tr>
<td>  
  <p>
	<%= s.label :'Amount'%><br>
	<%= s.number_field :amount %>
  </p>
</td> 

<td>  
</td> 

<td>  
  <p>
	<label>Converted</label><br>
	<input type="number" id="convertedval" name="convertedval" readonly= "readonly">
  </p>
</td> 
</tr> 

<tr>
<td>  
   <p>
	<%= s.label :'Commission'%><br>
	<%= s.number_field :comission, :value =>6 %>
   </p>
</td>
<td>
   <p>
	<input type="radio" id= "fx" name="com" value="fixed" checked="checked">Fixed<Br>
	<input type="radio" id= "pa"  name="com" value="percentage">Percentage
  </p>
</td> 
<td>  
  <p>
	<label>Commission</label><br>
	<input type="number" id="commval" name="commval" readonly= "readonly">
  </p>
</td> 
</tr>

<tr>
<td>
  <p>
	<%= s.label :'Total'%><br>
	<%= s.number_field :totalamt, :readonly => true %>
  </p>
</td>
</tr>
</table>  
 <p>
    <%= s.submit %>
  </p>

  
<% end %>


<%= link_to 'Back', currencies_path %>

app/views/transactions/newstockin.html.erb
<h1> Stock In </h1>
<%= form_for :transaction, url: tran_stockin_path do |s| %>

<% if @transaction.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited
      this transaction from being saved:</h2>
    <ul>
    <% @transaction.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
	<%= s.label :'Branch: '%>
	<%= @current_user.branch.name %>
  </p>

  <p>
	<%= s.label :'Currency Code'%><br>
	<%= collection_select(:transaction, :currency_id, Currency.all, :id, :currencycode, prompt: true) %>
  </p>
  
  <p>
	<%= s.label :'Amount'%><br>
	<%= s.text_field :amount %>
  </p>
  
  
 <p>
    <%= s.submit %>
  </p>
<% end %>

<%= link_to 'Back', currencies_path %>

app/views/transactions/show.html.erb
<p>
  <strong>Currency Name:</strong>
  <%= @transaction.currency.currencycode %>
</p>
<p>
  <strong>Branch Name:</strong>
  <%= @transaction.branch.name %>
</p>

<p>
  <strong>Total Amount:</strong>
  <%= @transaction.totalamt %>
</p>
<p>
  <strong>Transaction Type:</strong>
  <%= @transaction.trantype %>
</p>
